### ISSUE TITLE
episodeNumbers is array of +200 numbers

### ISSUE THREAD

**Issue by roblav96** [TypeCtrl/video-filename-parser#29]
<img width="757" alt="Screen Shot 2020-01-08 at 6 57 39 PM" src="https://user-images.githubusercontent.com/1457327/72026276-ec32ae80-3248-11ea-9cce-734536ce632f.png">

Examples:
`"Great British Railway Journeys S11E03 480p x264-mSD [eztv]"`
`"Radiant S02E14 480p x264-mSD [eztv]"`
`"This Hour Has 22 Minutes S27E11 480p x264-mSD [eztv]"`

**Comment by scttcper** [comment]
@roblav96 thanks for reporting this. Let me know of others you find. Project is still somewhat early especially with TV parsing.
