### ISSUE TITLE
Cannot parse season and episode

### ISSUE THREAD

**Issue by sayem314** [TypeCtrl/video-filename-parser#38]
input:

`Rick.And.Morty.s04e01.1080p.WEB.x264-worldmkv`

output:

```
 {
    title: 'Rick And Morty s04e01',
    year: null,
    resolution: '1080P',
    sources: [ 'WEBDL' ],
    videoCodec: 'x264',
    audioCodec: null,
    audioChannels: null,
    revision: { version: 1, real: 0 },
    group: 'worldmkv',
    edition: {
      imax: false,
      remastered: false,
      extended: false,
      theatrical: false,
      directors: false,
      unrated: false,
      fanEdit: false,
      limited: false,
      hdr: false,
      internal: false
    },
    languages: [ 'English' ],
    qualitySource: 'NAME',
    seasons: [],
    episodeNumbers: [],
    airDate: null,
    fullSeason: false,
    isPartialSeason: false,
    isMultiSeason: false,
    isSeasonExtra: false,
    isSpecial: false,
    seasonPart: 0,
    isTv: false,
  }
```

Also what is `qualitySource`? And why it is always `NAME`?

**Comment by scttcper** [comment]
looks like you parsed it as a movie, pass true to the second parameter. The qualitySource should usually be name as its parsed from the filename or path instead of the file extension. If there's no quality found in the name, it falls back to some assumptions of `.avi` vs `.mkv`

**Comment by sayem314** [comment]
Ah I see. It would be nice tho if it could automatically detect tv show name.

**Comment by scttcper** [comment]
I tried a little bit but gave up as i was frustrated with the edge cases. Opened #39
