### ISSUE TITLE
getting this error "Cannot find module 'tslib'" while using this in node

### ISSUE THREAD

**Issue by manishrawat4u** [TypeCtrl/video-filename-parser#43]
Error: Cannot find module 'tslib'
Require stack:
- /app/available_modules/1586634050000/@ctrl/video-filename-parser/dist/index.js
- /app/index.js

**Comment by scttcper** [comment]
Whoops, thanks for opening the issue

**Comment by manishrawat4u** [comment]
@scttcper awesome!!! thanks a ton.
